services:
  - type: web
    name: joblink-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: RESET_PASSWORD_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-large
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-west1-gcp
      - key: PINECONE_INDEX_NAME
        value: test-index
      - key: PINECONE_CLOUD_PROVIDER
        value: aws
      - key: PINECONE_REGION
        value: us-west-1
      - key: PINECONE_NAME_SPACE
        value: test-namespace
      - key: PINECONE_INDEX_HOST
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
